var n=true,r=null,u=false;
(function(j,w,A){j.la.Fb=function(a){var b={$a:200,p:{wa:j.i,ca:j.i},wa:function(c,e){var f=this,d=u;c.stop().fb({opacity:0},f.$a).H(function(){j(this).Qb().r("hide");f.p.wa.call(this);d||f.ca(c,e);d=n})},ca:function(c,e){var f=this;e.stop().n("hide").k(function(){f.p.ca.call(this)}).fb({opacity:1},f.$a)}};return this.k(function(){a&&j.extend(b,a);j(this).find(".tab").ja("opacity",0).r("hide").data("switch.settings",b)})};j.la.m=function(a){return this.k(function(){var b=j(this);b=j.type(a)=="string"?
b.find("#"+a):a;b.length&&"jquery"in b&&b.vb(".tab")||l.error("switch - ","Unknown slide:",a);var c=b.bc(".tab:not(.hide)"),e=b.data("switch.settings");c.length?e.wa(c,b):e.ca(c,b)})};j.la.blink=function(a){a=a||u;return this.k(function(){var b=j(this),c=j.data(this,"blink.timerID");if(c){clearInterval(c);j.$b(this,"blink.timerID");c=r}if(a!==u){c=b.text();var e,f=c.length;c=c.split("");for(e in c)c[e]="<span>"+c[e]+"</span>";b.empty().Ub(c.join("")).find("span").Ya(":eq(0)").ja("visibility","hidden");
e=1;c=setInterval(function(){if(e<f){b.find("span:eq("+e+")").ja("visibility","visible");e++}else{b.find("span").Ya(":eq(0)").ja("visibility","hidden");e=1}},a);j.data(this,"blink.timerID",c)}})};var x,l,k,m,t,y,o;if(!("console"in w))w.console={log:function(){},error:function(){}};if(!("Audio"in w))w.Jb=function(){this.pause=this.play=j.i;this.currentTime=0};Array.prototype.empty=Array.prototype.empty||function(){this.splice(0,this.length);return this};Array.prototype.Xa=Array.prototype.Xa||function(a){for(;a.length;)this.push(a.shift());
return this};Array.prototype.forEach=Array.prototype.forEach||function(a,b){if(this===void 0||this===r)throw new TypeError;var c=Object(this),e=c.length>>>0;if(typeof a!=="function")throw new TypeError;for(var f=0;f<e;f++)f in c&&a.call(b,c[f],f,c)};Math.Oa=Math.Oa||function(a){if(a<0)return-1;if(a>0)return 1;return 0};Math.ta=Math.ta||function(a,b){b=b||1;var c=Math.pow(10,b);return Math.round(a*c)/c};Math.ka=Math.ka||function(a,b){var c,e;if("x"in a&&"x"in b){c=b.x-a.x;e=b.y-a.y}else{c=b[0]-a[0];
e=b[1]-a[1]}return Math.sqrt(c*c+e*e)};if("WebSocket"in w)WebSocket.prototype.$=WebSocket.prototype.$||function(a,b,c){this["on"+a]=j.type(b)==="boolean"&&!b?this["on"+a]||c:b};l={Vb:u,a:{},z:{},ua:{},O:{},va:{},Db:1E3,key:{8:"backspace",9:"tab",13:"enter",16:"shift",17:"ctrl",18:"alt",19:"pause",27:"escape",32:"space",33:"page-up",34:"page-down",35:"end",36:"home",37:"left",38:"up",39:"right",40:"down",45:"insert",46:"delete",48:"0",49:"1",50:"2",51:"3",52:"4",53:"5",54:"6",55:"7",56:"8",57:"9",
65:"a",66:"b",67:"c",68:"d",69:"e",70:"f",71:"g",72:"h",73:"i",74:"j",75:"k",76:"l",77:"m",78:"n",79:"o",80:"p",81:"q",82:"r",83:"s",84:"t",85:"u",86:"v",87:"w",88:"x",89:"y",90:"z"},g:function(){j(w).Wb(function(a){var b=a.which;if(b in l.key&&!l.key[b].G){l.key[b].G=n;l.Ca(a,"down",b);l.cb(a,b)}}).Xb(function(a){var b=a.which;b in l.key&&l.Ca(a,"press",b)}).Yb(function(a){var b=a.which;if(b in l.key&&l.key[b].G){l.key[b].G=u;l.Ca(a,"up",b)}});j.k(l.key,function(a,b){l.key[a]={G:u,code:a};l.key[b]=
l.key[a]})},G:function(){for(var a=0;a<arguments.length;a++)if(!l.key[arguments[a]]||!l.key[arguments[a]].G)return u;return n},w:function(a,b){j.Va(a)||(a=a?[a]:[]);if(j.ma(b))b={L:b};a.length||l.error("io.bind - ","No keys to map");var c=l.Aa(a);c.length||l.error("io.bind - ","No valid keys to map");c.sort();var e=c.join(",");e in l.a&&delete l.a[e];l.a[e]={e:c,status:u,X:b.X,L:b.L,xa:b.xa};c.forEach(function(f){l.z[f]=l.z[f]||{};l.z[f][e]=l.a[e]})},Cb:function(a,b,c){j.Va(a)&&a.length||l.error("io.sequence - ",
"first param is not an array or is empty",a);j.ma(b)||l.error("io.sequence - ","second param is not a function",b);c=parseInt(c||l.Db,10);a=l.Aa(a);var e=a[0],f=a.join(",");if(f in l.ua){delete l.ua[f];delete l.O[e][f]}l.ua[f]={e:a,index:0,status:u,mb:c,la:b};l.O[e]=l.O[e]||{};l.O[e][f]=l.ua[f]},Ma:function(a){j.Va(a)||(a=a?[a]:[]);if(!a.length)return u;a=l.Aa(a);if(!a.length)return u;a.sort();var b=a.join(",");b in l.a&&delete l.a[b];a.forEach(function(c){delete l.z[c][b]});return n},Ca:function(a,
b,c){a.preventDefault=a.preventDefault||j.i;if(c in l.z)switch(b){case "down":j.k(l.z[c],function(f,d){if(l.G.apply(l,d.e)&&j.ma(d.X)){a.preventDefault();d.status=n;d.X()}});break;case "press":for(var e in l.z[c]){b=l.z[c][e];if(l.G.apply(l,b.e)&&j.ma(b.L)){a.preventDefault();b.L()}}break;case "up":j.k(l.z[c],function(f,d){if(d.status&&j.ma(d.xa)){a.preventDefault();d.xa();d.status=u}})}},cb:function(a,b){a.preventDefault=a.preventDefault||j.i;j.k(l.va,function(e,f){f(b)});if(b in l.O){var c=function(e,
f){f.index=0;delete l.va[e]};j.k(l.O[b],function(e,f){if(!(e in l.va)){f.index=1;l.va[e]=function(d,h){var g;return function(i){clearTimeout(g);if(h.e[h.index]!=i)c(d,h);else{h.index++;if(h.index==h.e.length){h.la();c(d,h)}else g=setTimeout(function(){c(d,h)},h.mb)}}}(e,f)}});a.preventDefault()}},Aa:function(a){var b=[];a.forEach(function(c){c in l.key?b.push(parseInt(l.key[c].code,10)):l.error("io.bind - ","Unknown key:",c)});return b}};l.g();x={now:function(){return+new Date}};y={e:{},add:function(a,
b){y.remove(a);y.e[a]=b;b.g=b.g||j.i;b.M=b.M||j.i},remove:function(a){a in y.e&&delete y.e[a]},c:function(a){if(a in y.e)return y.e[a];return r}};o={e:{},status:{},add:function(a,b){o.remove(a);o.e[a]=b;o.status[a]=u;b.status=function(c,e){return function(f){c.hb(e,f)}}(o,a)},remove:function(a){if(a in o.e){delete o.e[a];delete o.status[a]}},c:function(a){if(a in o.e)return o.e[a];return r},ac:function(){var a=[].slice.call(arguments),b=a.shift();(b=o.c(b))&&method in b&&b[method].apply(b,a)},N:function(){var a=
[].slice.call(arguments),b=a.shift();if(b)if(j.type(b)==="function")for(var c in o.e){var e=o.e[c];b.apply(e,a)}else if(j.type(b)==="string")for(c in o.e){e=o.e[c];b in e&&e[b].apply(e,a)}},ba:[],zb:function(a){o.ba.push(a)},clear:function(){for(;o.ba.length;)delete o.ba.shift()},hb:function(a,b){o.status[a]=!!b;for(var c in o.status)if(!o.status[c])return;for(;o.ba.length;)o.ba.shift()()}};k={h:r,id:0,error:u,Lb:{},a:{},sb:"ws://"+w.location.host+":8000",gb:w.location.pathname.replace(/\/[^\/]*$/,
"/"),g:function(){var a=this;if("WebSocket"in w){k.ab();var b=k.h=k.lb();b.$("message",u,function(c){var e=c.data,f;if(f=/^response\[([^\]]+)\](?::(.+))?$/.exec(e)){if(f[1]in a.a){a.a[f[1]].p.call(c,f[2]);a.a[f[1]].xb&&delete a.a[f[1]]}}else if(f=/^(.+?)(?::(.+))?$/.exec(e))f[1]in a.T&&a.T[f[1]].call(c,f[2])});b.$("error",u,function(c){"error"in a.a&&"callback"in a.a.error&&a.a.error.p.call(c)});b.$("close",u,function(c){"close"in a.a&&"callback"in a.a.close&&a.a.close.p.call(c)});b.$("open",u,function(c){"open"in
a.a&&"callback"in a.a.open&&a.a.open.p.call(c);a.qb();a.send("ping")})}},lb:function(){if("WebSocket"in w&&(!k.h||k.h.readyState>=WebSocket.Kb))k.h=new WebSocket(k.sb);return k.h},Sb:function(){k.h&&k.h instanceof WebSocket&&k.h.close()},Nb:function(){if(k.h&&"bufferedAmount"in k.h&&k.h.readyState===WebSocket.OPEN)return k.h.bufferedAmount===0;return u},Ba:[],send:function(a,b){(b=arguments.length>1?b:n)&&(!k.h||k.h.readyState!==WebSocket.OPEN)?k.H(a):k.h.send(a)},T:{},action:function(a,b){k.T[a]=
b},H:function(a){k.Ba.push(a)},qb:function(){for(;k.Ba.length;)k.h.send(k.Ba.shift())},ab:function(){k.a.id=k.a.id||{p:function(a){k.id=parseInt(a,10)}};k.a.open=k.a.open||{p:j.i};k.a.close=k.a.close||{p:j.i};k.a.error=k.a.error||{p:j.i}},w:function(){var a,b,c,e=n;if(arguments.length<2||!(a=/^(.+?)(?::(.+))?$/.exec(arguments[0])[1]))return u;switch(arguments.length){case 2:b=u;c=arguments[1]||j.i;break;case 3:b=arguments[1];c=arguments[2];break;case 4:b=arguments[1];e=arguments[2];c=arguments[3]}k.Ma(a);
k.a[a]={xb:b,p:c};e&&k.send(arguments[0]);return n},U:function(){if(arguments.length===2)return k.w(arguments[0],n,arguments[1]);return k.w(arguments[0],n,arguments[1],arguments[2])},La:function(){for(var a in arguments){var b=arguments[a];b in k.T&&delete k.T[b]}},Ma:function(){for(var a in arguments){var b=arguments[a];b in k.a&&delete k.a[b]}},url:function(a){return k.gb+a}};m={font:'10px "Trebuchet MS", Helvetica, Jamrul, sans-serif',screen:r,cc:{width:0,height:0},F:{id:r,Y:0,V:0,Qa:0,ub:20,Na:u},
g:function(){j(function(){m.screen=m.canvas(j("#game canvas.screen"))})},start:function(){m.stop();m.F.Na=n;m.loop()},stop:function(){clearTimeout(m.F.id);m.F.id=r;m.F.Y=0;m.F.Na=u},loop:function(){var a=m.F;a.Y=a.Y||x.now();a.V=x.now();a.Qa=a.V-a.Y;x.start("update-each");o.N("update",a.Qa,a.V);x.end("update-each");o.N("render");x.start("render-blit");m.screen.clearRect();m.screen.drawImage(o.c("maze").canvas.s,0,0);m.screen.drawImage(o.c("point").canvas.s,0,0);m.screen.drawImage(o.c("player").canvas.s,
0,0);m.screen.drawImage(o.c("text").canvas.s,0,0);x.end("render-blit");a.Y=a.V;if(m.F.Na){a=~~(m.F.ub-(x.now()-a.V));a=a>1?a:1;m.F.id=setTimeout(m.loop,a)}},canvas:function(a){if(a&&"jquery"in a)a=a.c(0);a||l.error("ui.canvas - ","empty object",a);if(!(this instanceof m.canvas))return new m.canvas(a);this.s=a;this.B=a.getContext("2d");if(!m.canvas.prototype.arc){m.canvas.prototype.c=function(){return this.s};m.canvas.prototype.A=function(){var e=A.createElement("canvas");e.width=this.s.width;e.height=
this.s.height;return m.canvas(e)};var b=["arc","arcTo","beginPath","bezierCurveTo","clip","closePath","drawFocusRing","drawImage","fill","fillRect","fillText","lineTo","moveTo","putImageData","quadraticCurveTo","rect","restore","rotate","save","scale","setTransform","stroke","strokeRect","strokeText","transform","translate"];m.canvas.prototype.clearRect=function(){if(arguments.length)this.B.clearRect.apply(this.B,arguments);else this.s.width&&this.s.height&&this.B.clearRect(0,0,this.s.width,this.s.height);
return this};for(a=0;a<b.length;a++){var c=b[a];m.canvas.prototype[c]=function(e){return function(){this.B[e].apply(this.B,arguments);return this}}(c)}b=["createImageData","createLinearGradient","createRadialGradient","createPattern","getImageData","isPointInPath","measureText"];for(a=0;a<b.length;a++){c=b[a];m.canvas.prototype[c]=function(e){return function(){return this.B[e].apply(this.B,arguments)}}(c)}b=["canvas","fillStyle","font","globalAlpha","globalCompositeOperation","lineCap","lineJoin",
"lineWidth","miterLimit","shadowOffsetX","shadowOffsetY","shadowBlur","shadowColor","strokeStyle","textAlign","textBaseline"];for(a=0;a<b.length;a++){c=b[a];m.canvas.prototype[c]=function(e){return function(f){if(typeof f==="undefined")return this.B[e];this.B[e]=f;return this}}(c)}}},R:r,J:r,info:function(a,b){m.R=m.R||j("#infos").Fa(".links a","click",function(){j("#infos").r("hide")});var c=m.R.find("p:first"),e=m.R.find(".links");c.text(a);e.empty();j.k(b,function(f,d){e.append(j("<a>").text(f).click(d||
j.i))});m.R.n("hide")},error:function(a,b){m.J=m.J||j("#errors").Fa(".links a","click",function(){j("#errors").r("hide")});var c=m.J.find("p:first"),e=m.J.find(".links");c.text(a);e.empty();j.k(b,function(f,d){e.append(j("<a>").text(f).click(d||j.i))});m.J.ja("top",(480-m.J.outerHeight())/2).n("hide")}};m.g();t={b:r,data:r,g:function(a){t.b=a;t.data=o.c("maze").data},move:function(a,b){var c=a.Ib*b,e;c=(e=Math.sqrt(a.Ga*a.Ga+a.Ha*a.Ha))?c/e:c;a.ra=a.x;a.x+=a.Ga*c;a.sa=a.y;a.y+=a.Ha*c;t.tb(a)},db:{x:0,
y:0,fa:u,ga:u,reset:function(){this.y=this.x=0;this.ga=this.fa=u}},j:[{da:0,ea:1},{da:-1,ea:0},{da:0,ea:-1},{da:1,ea:0}],I:[{},{},{},{}],jb:function(a){var b,c,e,f,d,h,g,i,p,q=t.db,v=t.data,s;e=a.x;f=a.y;d=t.b.o;h=a.aa;q.reset();b=Math.floor(e/d);c=Math.floor(f/d);if(!(v[c]&&v[c][b]))return q;s=v[c][b];g=d*b;i=d*c;p=g+d;cyh=i+d;d=t.j[0];d.K=f-h-i;d.ha=s[0];d.q=u;d=t.j[1];d.K=p-(e+h);d.ha=s[1];d.q=u;d=t.j[2];d.K=cyh-(f+h);d.ha=s[2];d.q=u;d=t.j[3];d.K=e-h-g;d.ha=s[3];d.q=u;for(var z in t.j){d=t.j[z];
if(d.K<0){d.q=n;if(d.ha){q.x-=d.da*d.K;q.y-=d.ea*d.K;q.fa=q.fa||!!d.da;q.ga=q.ga||!!d.ea}}}if(q.x||q.y)return q;s=t.I[0];s.x=g;s.y=i;s.ya=t.j[0].q&&t.j[3].q&&(v[c-1][b][3]||v[c][b-1][0]);s=t.I[1];s.x=p;s.y=i;s.ya=t.j[0].q&&t.j[1].q&&(v[c-1][b][1]||v[c][b+1][0]);s=t.I[2];s.x=g;s.y=cyh;s.ya=t.j[2].q&&t.j[3].q&&(v[c+1][b][3]||v[c][b-1][2]);s=t.I[3];s.x=p;s.y=cyh;s.ya=t.j[1].q&&t.j[2].q&&(v[c+1][b][1]||v[c][b+1][2]);for(z in t.I){s=t.I[z];if(s.ya){b=Math.ka(a,s);if(b<=h){b=b?h/b-1:h;q.x-=b*(s.x-e);q.y-=
b*(s.y-f)}}}return q},tb:function(a){var b=a.x-a.ra,c=Math.abs(b),e=Math.Oa(b),f=a.y-a.sa,d=Math.abs(f),h=Math.Oa(f),g=u,i=u;if(b||f){if(c>d){for(b=c;b>1;)b/=2;f=c;e=b*e;h=d*b/c*h}else{for(b=d;b>1;)b/=2;f=d;h=b*h;e=c*b/d*e}a.x=a.ra;a.y=a.sa;for(c=0;c<f;c+=b){g||(a.x+=e);i||(a.y+=h);d=t.jb(a);a.x+=d.x;a.y+=d.y;g=g||d.fa;i=i||d.ga;if(g&&i)break}}}};o.add("maze",function(){var a;return{canvas:r,b:{},data:[],g:function(b){this.canvas=this.canvas||m.screen.A();this.b=b;this.status(n)},wb:function(b){var c=
this;a&&"abort"in a&&a.abort();c.b=y.c("game").b;a=j.Tb(b,function(e){var f=c.b,d=c.data,h;j.extend(n,c.b,e.b);f.width=f.cols*f.o;f.height=f.rows*f.o;c.data.empty().Xa(e.data);f.f={};for(var g=0;g<f.rows;g++){if(j.type(d[g])!=="array")d[g]=[];for(var i=0;i<f.cols;i++){e=d[g][i];if(e[2]){h=e[2];f.f[g]=f.f[g]||{};f.f[g][i]=[h];switch(h[0]){case "1":f.Eb[h[1]]=[g,i];break;case "2":f.f[g][i][1]=e[3]||r}}d[g][i]=[g?d[g-1][i][2]:1,f.cols-i-1?e[0]||0:1,f.rows-g-1?e[1]||0:1,i?d[g][i-1][1]:1]}}o.N("dataReady",
f)})},start:function(){this.nb()},nb:function(){var b=this.canvas,c=this.b,e=this.data,f=c.margin,d=c.margin,h=c.o,g,i,p;b.clearRect();b.strokeStyle("#000").fillStyle("#fff").lineWidth(1).fillRect(f,d,c.width,c.height).beginPath();for(var q=0;q<c.rows;q++)for(var v=0;v<c.cols;v++){p=e[q][v];g=f+h*v;i=d+h*q;g=[{x:g,y:i},{x:g+h,y:i},{x:g+h,y:i+h},{x:g,y:i+h}];for(i=0;i<4;i++)if(p[i])b.moveTo(g[i].x,g[i].y).lineTo(g[i<3?i+1:0].x,g[i<3?i+1:0].y)}b.stroke()}}}());o.add("player",function(){var a={x:0,y:0},
b=[3,10],c=[3,7],e=j(w),f=e.width()/e.height();return{id:0,l:1,canvas:r,b:{},data:[],Ja:r,v:r,Ua:u,Pa:r,C:{},d:{za:u,D:0,u:0},W:0,Ea:0,g:function(d){var h=this;this.reset();this.canvas=this.canvas||m.screen.A();this.b=d;this.data=o.c("maze").data;this.Ja=o.c("point");[{na:"up",S:"y",Z:-1},{na:"down",S:"y",Z:+1},{na:"left",S:"x",Z:-1},{na:"right",S:"x",Z:+1}].forEach(function(g){l.w(g.na,{X:function(){h.v["f"+g.S]+=g.Z},L:j.i,xa:function(){h.v["f"+g.S]-=g.Z}})});l.w("space",{X:function(){h.capture()},
L:j.i});this.eb();this.status(n);e.yb("resize",function(){var g=j(this);g=g.width()/g.height();if(Math.abs(f-g)<=0.2)h.d.za=n})},eb:function(){var d=o.c("point"),h=this.b,g=this.v,i;for(i in d.f)for(var p in d.f[i]){var q=d.f[i][p];if(q.type==1&&this.l==q.pa){g.x=g.ra=h.o*parseInt(p,10)+h.margin-g.aa/2;g.y=g.sa=h.o*parseInt(i,10)+h.margin-g.aa/2}else q.type==2&&this.l==q.pa&&this.Ea++}},reset:function(){this.v={x:15,y:15,ra:15,sa:15,Ga:0,Ha:0,Ib:120,aa:7};this.C={};this.d.D=this.d.u=0;this.d.za=u;
this.Ea=this.W=0},bb:[],capture:function(){var d=this.b,h=this.v,g=this.Ja,i=this.bb,p;i[0]=Math.floor(h.x/d.o);i[1]=Math.floor(h.y/d.o);if(g.f[i[1]]&&g.f[i[1]][i[0]]){p=g.f[i[1]][i[0]];if(p.pa===this.l)if(this.W+1==p.Q){g.H.push(i);k.send("clear:"+JSON.stringify(i));this.W=p.Q;if(this.Ea==this.W){k.send("finished:"+this.l);k.send("silent-leave-channel");this.Sa(n)}}else{if(Math.ka(a,h)>=d.o/2){this.d.D++;a.x=h.x;a.y=h.y}}else if(Math.ka(a,h)>=d.o/2){this.d.u++;p.Q&&this.W+1==p.Q&&this.d.D++;a.x=
h.x;a.y=h.y}}},Sa:function(d,h){var g=this;if(d)if(g.d.u>=b[0]&&g.d.u<=b[1])m.info("Wygra\u0142e\u015b! Przejd\u017a dalej zobaczy\u0107 komunikat.",{Dalej:function(){var i=j("#info-colorblind").find("a[href]"),p=i.t("href");p=p.replace(/^([^\?]+).*$/,"$1?flaw="+o.c("point").P+"&value="+g.d.u);i.t("href",p);l.log(p);j("#container").m("info-colorblind")}});else g.d.D>=c[0]&&g.d.D<=c[1]||g.d.za?m.info("Wygra\u0142e\u015b! Przejd\u017a dalej zobaczy\u0107 komunikat.",{Dalej:function(){var i=j("#info-myopia").find("a[href]"),
p=i.t("href");p=p.replace(/^([^\?]+).*$/,"$1?flaw=myopia&value="+g.d.D);i.t("href",p);l.log(p);j("#container").m("info-myopia")}}):m.info("Wygra\u0142e\u015b!",{"Wr\u00f3\u0107 do listy serwer\u00f3w":function(){j("#container").m("servers")}});else if(g.d.u>=b[0]&&g.d.u<=b[1])m.info("Gracz "+h+" wygra\u0142! Przejd\u017a dalej zobaczy\u0107 komunikat.",{Dalej:function(){k.send("silent-leave-channel");var i=j("#info-colorblind").find("a[href]"),p=i.t("href");p=p.replace(/^([^\?]+).*$/,"$1?flaw="+o.c("point").P+
"&value="+g.d.u);i.t("href",p);l.log(p);j("#container").m("info-colorblind")}});else g.d.D>=c[0]&&g.d.D<=c[1]||g.d.za?m.info("Gracz "+h+" wygra\u0142! Przejd\u017a dalej zobaczy\u0107 komunikat.",{Dalej:function(){k.send("silent-leave-channel");var i=j("#info-myopia").find("a[href]"),p=i.t("href");p=p.replace(/^([^\?]+).*$/,"$1?flaw=myopia&value="+g.d.D);i.t("href",p);l.log(p);j("#container").m("info-myopia")}}):m.info("Gracz "+h+" wygra\u0142!",{"Wr\u00f3\u0107 do listy serwer\u00f3w":function(){k.send("silent-leave-channel");
j("#container").m("servers")}})},update:function(d){x.start("update-player");t.move(this.v,d*0.0010);x.end("update-player")},Ab:function(){var d=this.b,h=this.Ja,g=this.v,i=this.canvas,p=h.ia[h.P];i.clearRect().lineWidth(1).strokeStyle("#000");x.start("render-opps");j.k(this.C,function(q,v){var s=d.margin,z=g.aa;i.beginPath().fillStyle(p[h.oa][0]).arc(s+v.x,s+v.y,z,0,Math.PI*2,n).fill().stroke().closePath();z=i.font(m.font).measureText(v.l);i.fillStyle(p[2]).fillText(v.l,s+v.x-z.width/2,s+v.y+parseInt(m.font,
10)*0.35)});x.end("render-opps");x.start("render-ball");i.beginPath().fillStyle(p[h.qa][0]).arc(d.margin+g.x,d.margin+g.y,g.aa-0.5,0,Math.PI*2,n).fill().stroke().closePath();x.end("render-ball")}}}());o.add("point",function(){return{canvas:r,b:{},f:{},ia:{Zb:[["#ba0003","#b20003","#b30003","#b40003","#b60003","#b80003","#bc0003","#be0003","#c00003","#c10003","#c20003"],["#006001","#005a01","#005b01","#005c01","#005d01","#005e01","#006201","#006301","#006401","#006501","#006601"],"#fff"],Rb:[["#fa5507",
"#f25507","#f35507","#f45507","#f65507","#f85507","#fb5507","#fc5507","#fd5507","#fe5507","#ff5507"],["#006c02","#006602","#006702","#006802","#006a02","#006b02","#006d02","#006e02","#006f02","#007102","#007202"],"#fff"],ec:[["#18f0df","#18f0cc","#18f0ce","#18f0d1","#18f0d6","#18f0d9","#18f0e3","#18f0e6","#18f0e8","#18f0ea","#18f0ef"],["#0dff35","#0dff0d","#0dff11","#0dff20","#0dff27","#0dff2c","#0dff3f","#0dff4b","#0dff52","#0dff58","#0dff5d"],"#000"]},kb:"#e5e5e5",P:r,qa:0,oa:1,u:r,H:[],g:function(a){this.canvas=
this.canvas||m.screen.A();this.b=a;this.status(n)},Bb:function(){var a=[],b;for(b in this.ia)a.push(b);return a[Math.round(Math.random()*(a.length-1))]},Pb:function(a){this.f={};for(var b in a.f)for(var c in a.f[b]){point=a.f[b][c][0];value=a.f[b][c][1];this.f[b]=this.f[b]||{};this.f[b][c]={type:parseInt(point[0],10),pa:parseInt(point[1],10),Q:parseInt(value,10)||r}}},start:function(){this.P=this.Bb();this.u=this.ia[this.P];if(Math.random()>=0.5){this.qa=0;this.oa=1}else{this.qa=1;this.oa=0}this.ob()},
update:function(){var a;for(x.start("update-point");this.H.length>0;){a=this.H.shift();this.ib(a[0],a[1])}x.end("update-point")},ob:function(){var a=this.f,b,c=o.c("player"),e=this.ia[this.P],f;this.canvas.clearRect();var d=0,h;for(h in a)for(var g in a[h]){b=a[h][g];if(b.type===2){d++;f=c.l==b.pa?this.qa:this.oa;this.Ra(g,h,e[f][b.Q],b.Q,e[2])}}},Ra:function(a,b,c,e,f){var d=this.b,h=this.canvas,g=d.o;d=d.margin;h.clearRect(d+a*g,d+b*g,g,g);h.drawImage(this.rb(c),d+a*g,d+b*g);e=e||r;f=f||"#fff";
if(e!==r){c=h.measureText(e);h.font(m.font).fillStyle(f).fillText(e,d+a*g+(g-c.width)/2,d+b*g+(g+Math.floor(parseInt(m.font,10)*0.75))/2)}},ib:function(a,b){this.Ra(a,b,this.kb)},Ka:{},rb:function(a){if(this.Ka[a])return this.Ka[a];var b,c=this.b.o,e=c*0.1;b=c*0.6;var f=e+e,d=f+b,h=d+e,g=e+e,i=g+b,p=i+e;b=this.Ka[a]=A.createElement("canvas");b.width=b.height=c;m.canvas(b).fillStyle(a).beginPath().moveTo(f,e).lineTo(d,e).arc(d,g,e,Math.PI*1.5,0,u).lineTo(h,i).arc(d,i,e,0,Math.PI*0.5,u).lineTo(f,p).arc(f,
i,e,Math.PI*0.5,Math.PI,u).lineTo(e,g).arc(f,g,e,Math.PI,Math.PI*1.5,u).closePath().fill();return b}}}());o.add("text",function(){return{canvas:r,b:{},Ta:0,pb:0,g:function(a){this.canvas=this.canvas||m.screen.A();this.b=a;this.status(n)},update:function(a){this.Ta=Math.round(1E4/a)/10;this.pb=Math.ta(a,3)},Ab:function(){var a=this.b,b=this.canvas;x.start("render-text");b.clearRect().font(m.font).fillStyle("#000").fillText("fps: "+this.Ta,a.margin,13)}}}());y.add("intro",function(){return{g:function(){var a=
j("#intro").find(">div").Ia();a.filter(".testing").Ia();if(this.test()){a.Ia();a.filter(".ready").show()}else{a.Ia();a.filter(".fail").show()}},test:function(){return"WebSocket"in w&&!!A.createElement("canvas").getContext}}}());y.add("connect",function(){return{g:function(){k.U("open",function(){j("#container").m("servers")});k.U("close",function(){m.error("Serwer nie odpowiada",{"Pon\u00f3w pr\u00f3b\u0119":function(){k.g()}})});k.g();j("#connect span.dots").blink(u).blink(400)},M:function(){j("#connect span.dots").blink(u)}}}());
y.add("limbo",function(){var a=new Audio(k.url("audios/ping.ogg"));return{g:function(){var b=o.c("player"),c=j("#limbo"),e=c.find("ul"),f=u;id=j("#limbo").data("channel-id");c.find("span.dots").blink(u).blink(400).end().find("a[data-switch-to]").Gb(".go-back").yb("click.go-back",function(){f=n;k.send("leave-channel")}).end().find(".countdown").empty();e.find(".you").n("ready").r("not-ready").find("a[data-change-status]").n("unclickable").Gb("click").click(function(){var d=j(this);if(d.vb(".unclickable"))return u;
d=d.data("change-status");e.find(".you").n("ready not-ready").r(d);k.send("change-status:"+d);return u});e.find("li").Ya(".you, .hide").remove();k.action("status-changed",function(d){d=JSON.parse(d);e.find(".opponent[data-id="+d.id+"]").n("ready not-ready").r(d.status?"ready":"not-ready")});k.action("start-game",function(d){d=JSON.parse(d);var h=1E3;d=x.now()-d.dc;h-=d;var g=c.find(".countdown").empty();e.find("a[data-change-status]").r("unclickable");setTimeout(function(){var i=Math.ta(h/1E3),p=
Math.ceil(i);i=/^\d+\.\d+$/.test(""+i)?i:i+".0";h-=100;g.text(i);var q=w.setInterval(function(){if(f){f=u;c.find(".countdown").empty();w.clearInterval(q)}else{h-=100;if(h<0){w.clearInterval(q);j("#container").m("game")}else{i=Math.ta(h/1E3);if(p>Math.ceil(i)){p=Math.ceil(i);if(a){a.currentTime=0;a.play()}}i=/^\d+\.\d+$/.test(""+i)?i:i+".0";g.text(i)}}},100)},100-d)});k.action("quit",function(d){e.find(".opponent[data-id="+d+"]").remove();e.find(".waiting:last").Da(e.find(".waiting:first").A().n("hide"));
j(".you").n("ready").r("not-ready").find(".unclickable").n("unclickable");k.send("change-status:not-ready");f=n});k.action("joined-channel",function(d){d=JSON.parse(d);if(d.id!=k.id){e.find(".waiting:last").remove();e.find(".opponent:last").Da(e.find(".opponent:first").A().n("hide").r("not-ready").t("data-id",d.id))}});k.U("get-channel-info:"+b.Pa,n,function(d){d=JSON.parse(d);var h=d.Za,g=c.find("ul");setTimeout(function(){o.c("maze").wb(k.url(d.map))},100);for(var i=0,p=d.Wa-d.Ob;i<p;i++)g.find(".waiting:last").Da(g.find(".waiting:first").A().n("hide"));
h.forEach(function(q){if(q.id==k.id)return n;var v=g.find(".opponent:first").A();v.t("data-id",q.id);v.n("hide").r(q.status?"ready":"not-ready");g.find(".opponent:last").Da(v)})})},M:function(){j("#limbo span.dots").blink(u);k.La("status-changed","start-game","quit","joined-channel")}}}());y.add("servers",function(){var a,b,c;$schema=j('<li data-channel-id="{#id}"><div class="name">{#name}</div><div class="players">{#players}/{#limit}</div><a data-channel-id="{#id}">Do\u0142\u0105cz</a></li>');return{update:function(e){var f=
{};e=JSON.parse(e);j.k(e,function(d,h){f[h.id]=h});c.r("hide");b.find("li").k(function(){var d=j(this),h=d.data("channel-id");if(h in f){d.find(".name").text(f[h].name);d.find(".players").text(f[h].Za+"/"+f[h].Wa);delete f[h]}else d.remove()});j.k(f,function(d,h){var g=$schema.A();g.find(".name").text(h.name).end().find(".players").text(h.Za+"/"+h.Wa).end().find("a").Mb().t("data-channel-id",h.id);b.append(g)});b.find("li[data-channel-id]").length||c.n("hide")},g:function(){b=b||j("#servers ul").Fa("a",
"click",function(){var e=j(this),f=o.c("player"),d=e.data("channel-id");if(!d)return u;k.U("join-channel:"+d,n,function(h){h=JSON.parse(h);var g=h[1]?parseInt(h[1],10):r;switch(parseInt(h[0],10)){case 1:f.Ua=n;f.l=g;f.Pa=d;j("#container").m("limbo");break;case -3:m.info("Gra w toku",{Ok:r});break;case -2:m.info("Brak wolnych miejsc",{Ok:r});break;case -1:m.error("Taki kana\u0142 nie istnieje",{Ok:r})}});return u});c=c||b.parent().find(".no-servers").find(".dots").blink(400).end();k.U("close",function(){m.error("Utracono po\u0142\u0105czenie z serwerem",
{"Po\u0142\u0105cz ponownie":function(){j("#container").m("connect")}})});k.w("get-channels",this.update);a=setInterval(function(){k.send("get-channels",u)},2E3)},M:function(){k.Ma("get-channels");clearInterval(a)}}}());y.add("game",function(){var a,b={id:0,l:0,x:0,y:0};return{Hb:50,b:{width:r,height:r,o:30,margin:20,cols:25,rows:15,f:{},Eb:{}},g:function(){var c=this,e=o.c("point"),f=o.c("player");if(f.Ua){k.action("update",function(d){d=JSON.parse(d);if(d.id&&d.id!=k.id){f.C[d.id]=f.C[d.id]||{l:0,
x:15,y:15};f.C[d.id].l=d.l;f.C[d.id].x=d.x;f.C[d.id].y=d.y}});k.action("clear",function(d){e.H.push(JSON.parse(d))});k.action("finished",function(d){d=parseInt(d,10);k.La("quit");k.send("silent-leave-channel");f.Sa(u,d)});k.action("quit",function(d){d in f.C&&delete f.C[d];m.info("Jeden z graczy wyszed\u0142. Gra zostaje przerwana.",{"Wr\u00f3\u0107 do listy serwer\u00f3w":function(){k.send("silent-leave-channel");j("#container").m("servers")}})});o.zb(function(){t.g(c.b);o.N("start");m.start();b.l=
f.l;b.id=k.id;a=w.setInterval(function(){b.x=f.v.x;b.y=f.v.y;k.send("update:"+JSON.stringify(b))},c.Hb)});o.N("init",c.b)}else j("#container").m("servers")},M:function(){m.stop();o.clear();a&&w.clearInterval(a);k.La("update","clear","finished","quit");o.N("stop")}}}());var B=new Audio(k.url("audios/contra.ogg"));l.Cb(["up","up","down","down","left","right","left","right","b","a","enter"],function(){B.play()});l.w("escape",function(){B.pause();B.currentTime=0});j(function(){var a=j("#container"),b=
a.find(":first"),c=w.location.hash;a.Fb({p:{wa:function(){var e=y.c(this.id);e&&e.M()},ca:function(){var e=y.c(this.id);e&&e.g()}}}).Fa("a[data-switch-to]","click",function(){a.m(j(this).data("switch-to"));return u});if(c.length)b=a.find(c+".tab");a.m(b);["1","2","3","4"].forEach(function(e,f){l.w(e,function(){a.find(".tab:not(.hide)").find("a:eq("+f+")").click()})});l.w("enter",function(){a.find(".popup:not(.hide) p.links>a:first").click()})})})(jQuery,window,window.document);
