#!/bin/bash
FILES="
../client/scripts/jquery.plugins.js
../client/scripts/base.js
../client/scripts/io.js
../client/scripts/net.js
../client/scripts/ui.js
../client/scripts/phy.js
../client/scripts/player.js
../client/scripts/text.js
../client/scripts/client.js"

TMP=mktemp
MINIMIZED="../client/scripts/minimized.js"

CONTENT=`cat $FILES`
echo "(function($){$CONTENT})(jQuery);" > $TMP

java -jar ./compiler.jar --js=$TMP --js_output_file=$MINIMIZED
rm $TMP

