#!/bin/bash

MYPATH=`dirname $0`

FILES="
$MYPATH/../client/scripts/jquery.plugins.js
$MYPATH/../client/scripts/base.js
$MYPATH/../client/scripts/io.js
$MYPATH/../client/scripts/net.js
$MYPATH/../client/scripts/ui.js
$MYPATH/../client/scripts/phy.js
$MYPATH/../client/scripts/player.js
$MYPATH/../client/scripts/text.js
$MYPATH/../client/scripts/client.js"

TMP=mktemp
MINIMIZED="$MYPATH/../client/scripts/minimized.js"

CONTENT=`cat $FILES`
echo "(function($){$CONTENT})(jQuery);" > $TMP

java -jar $MYPATH/compiler.jar --js=$TMP --js_output_file=$MINIMIZED
rm $TMP

echo "Done!"